/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev`/`next build`.
// It is checked in here as a placeholder so `tsc --noEmit` has the ambient
// types available even before the first local `next dev` run.
